### ISSUE TITLE
Provide a method to promote/demote adaptively

### ISSUE THREAD

**Issue by Liffon** [vikpe/php-html-heading-normalizer#1]
In my use case, it's unknown which heading level is lowest in a given document. I would like a method that could take (for example) either
```html
<h2>Biggest header</h2>
<h3>Smaller header</h2>
```
or
```html
<h3>Biggest header</h3>
<h4>Smaller header</h4>
```
and in both cases give the same output.

In essence, I'm looking for a way to say "regardless of what level the headings start on in this document, make sure the lowest level is `<hX>`".

**Comment by vikpe** [comment]
5e3efe5 - Added `min(string $html, int $minLevel)` - Adjusts all headings in `$html` so that the lowest heading level equals `$minLevel`.
